# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "quenty/rojo@7.3.0-quenty-npm-canary.7"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
selene = "Kampfkarren/selene@0.25.0"
moonwave-extractor = "UpliftGames/moonwave@1.0.1"
mantle = "blake-mealey/mantle@0.10.7"
remodel = "rojo-rbx/remodel@0.9.1"